project:
  type: website

# Default formats and options for the project
format:
  revealjs:
    theme: moon
    transition: fade
    widescreen: true

# Render into docs/ so the repo can be published with GitHub Pages
site:
  output-dir: docs

# Global execution options
execute:
  echo: true
  warning: false
  error: false

# Simple navbar for the generated site
website:
  title: "Reproducing the whole-plant economics spectrum"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Notes
        href: Notes/
    right: []
